name: 'Trigger webhook'
description: 'Used to send POST HTTP requests to a webhook'
inputs:
  url:
    description: 'URL to send the request to'
    required: true
  json:
    description: 'JSON to send in the request body'
    required: false
    default: '{}'
  headers:
    description: 'Headers to send in the request'
    required: false
    default: '{}'
author: 'Mateusz Wejman'
runs:
  using: 'node16'
  main: 'dist/index.js'
